### ISSUE TITLE
不能用了吗？

### ISSUE THREAD

**Issue by Gu-f** [AnHiAo/QQ_XML_Discover#1]
我测试发出去的<>好像都变中文了？，无法解析。

**Comment by AnHiAo** [comment]
请检查是否是你的操作问题或者具体是哪个卡片的代码出现无法解析

**Comment by Gu-f** [comment]
就第一个社交视频分享xml，这个我复制从聊天窗口发出去后没有生效

**Comment by AnHiAo** [comment]
那是你选择发送xml的工具没有解析正确,请自行解决找到能够发送xml卡片的工具。第一个社交视频的xml卡片目前依然能够正确显示在QQ上的
